# Najpierw uruchom aplikacje: docker compose up -d
@host = http://localhost:8080

### czy aplikacja zyje - zawsze 200
GET {{host}}/health

### czy przyjmuje ruch - 503 w trakcie zamykania
GET {{host}}/ready

### odczyt licznika
GET {{host}}/counter

### +1
POST {{host}}/counter/increment

### -1
POST {{host}}/counter/decrement

### zerowanie
POST {{host}}/counter/reset

### 405 - zla metoda pod dobrym adresem.
### W /metrics ma sie pokazac jako status="405".
GET {{host}}/counter/increment

### 404 - nieznany adres. W /metrics wszystkie takie ida do jednego
### worka path="/{unmatched}".
GET {{host}}/nie-ma-takiego

### drugie 404 - sprawdz, ze nie zrobilo osobnej metryki
GET {{host}}/tez-nie-ma

### metryki w formacie Prometheusa
GET {{host}}/metrics
