name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Cache SBT
        uses: actions/cache@v3
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
          key: sbt-${{ hashFiles('01-kalkulator/build.sbt') }}

      - name: Compile
        run: cd 01-kalkulator && sbt compile

      - name: Test
        run: cd 01-kalkulator && sbt test